#!/bin/sh
# bootstrap.sh — set up unveil from scratch on a fresh server
#
# Usage: sh bootstrap.sh [site.conf]
#
# Reads site.conf, installs dependencies, creates directories,
# generates web server config, sets up TLS, and runs initial setup.
#
# Supports: OpenBSD, Debian/Ubuntu, RHEL/CentOS/Fedora, Alpine, macOS

set -e

[ "$(id -u)" -eq 0 ] || { echo "Run as root." >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONF="${1:-$SCRIPT_DIR/site.conf}"
[ -f "$CONF" ] || { echo "Error: site.conf not found: $CONF" >&2; exit 1; }

# ── Load config ───────────────────────────────────────────────────────────
_domain="$(grep '^DOMAIN=' "$CONF" | head -1 | cut -d= -f2)"
[ -n "$_domain" ] || { echo "Error: DOMAIN not set in $CONF" >&2; exit 1; }
eval "$(grep -v '^#' "$CONF" | grep '=' | sed "s/\\\$DOMAIN/$_domain/g")"

: "${HTTPD:=none}"
: "${TLS:=none}"
: "${UTILS_DIR:=/var/www/utils/$DOMAIN}"
: "${HTDOCS_DIR:=/var/www/htdocs/$DOMAIN}"
: "${GPG_EMAIL:=admin@$DOMAIN}"

echo "=== unveil bootstrap: $DOMAIN ==="
echo "  Server:  $HTTPD"
echo "  TLS:     $TLS"
echo "  Utils:   $UTILS_DIR"
echo "  Htdocs:  $HTDOCS_DIR"
echo

# ── Detect OS ─────────────────────────────────────────────────────────────
detect_os() {
    if [ "$(uname)" = "OpenBSD" ]; then echo "openbsd"
    elif [ -f /etc/debian_version ]; then echo "debian"
    elif [ -f /etc/redhat-release ]; then echo "rhel"
    elif [ -f /etc/alpine-release ]; then echo "alpine"
    elif [ "$(uname)" = "Darwin" ]; then echo "macos"
    else echo "unknown"
    fi
}
OS=$(detect_os)
echo "  OS:      $OS"
echo

# ── Install dependencies ─────────────────────────────────────────────────
echo "--- Dependencies ---"
case "$OS" in
    openbsd)
        for pkg in python3 gnupg; do
            command -v "$pkg" >/dev/null 2>&1 || pkg_add "$pkg" 2>/dev/null
        done
        python3 -c "from cryptography.hazmat.primitives.ciphers.aead import AESGCM" 2>/dev/null || \
            pkg_add py3-cryptography 2>/dev/null
        ;;
    debian)
        apt-get update -qq
        apt-get install -y -qq python3 python3-cryptography gnupg
        ;;
    rhel)
        yum install -y python3 python3-cryptography gnupg2
        ;;
    alpine)
        apk add python3 py3-cryptography gnupg
        ;;
    macos)
        command -v python3 >/dev/null 2>&1 || brew install python3
        command -v gpg >/dev/null 2>&1 || brew install gnupg
        pip3 install cryptography 2>/dev/null || true
        ;;
    *)
        echo "  Unknown OS — install python3, cryptography, and gnupg manually."
        ;;
esac
echo "  OK"
echo

# ── Copy scripts to UTILS_DIR ────────────────────────────────────────────
echo "--- Installing scripts ---"
mkdir -p "$UTILS_DIR"
for f in locksite.py merge.sh setup.sh gen-passphrase.sh decrypt.py \
         verify-html.sh DECRYPT-README.txt; do
    [ -f "$SCRIPT_DIR/$f" ] && cp "$SCRIPT_DIR/$f" "$UTILS_DIR/$f"
done
cp "$CONF" "$UTILS_DIR/site.conf"
chmod +x "$UTILS_DIR"/*.sh 2>/dev/null || true
echo "  Scripts -> $UTILS_DIR/"
echo

# ── Create directories ────────────────────────────────────────────────────
echo "--- Directories ---"
mkdir -p "$HTDOCS_DIR"
mkdir -p "$UTILS_DIR"
echo "  $UTILS_DIR/"
echo "  $HTDOCS_DIR/"
echo

# ── Web server configuration ─────────────────────────────────────────────
install_certbot() {
    command -v certbot >/dev/null 2>&1 && return
    case "$OS" in
        debian) apt-get install -y -qq certbot ;;
        rhel)   yum install -y certbot ;;
        alpine) apk add certbot ;;
        macos)  brew install certbot ;;
    esac
}

set_htdocs_owner() {
    case "$HTTPD" in
        openbsd-httpd) chown www:www "$HTDOCS_DIR" 2>/dev/null || true ;;
        nginx)  chown www-data:www-data "$HTDOCS_DIR" 2>/dev/null || \
                chown nginx:nginx "$HTDOCS_DIR" 2>/dev/null || true ;;
        apache) chown www-data:www-data "$HTDOCS_DIR" 2>/dev/null || \
                chown apache:apache "$HTDOCS_DIR" 2>/dev/null || true ;;
    esac
}

# ── OpenBSD httpd ─────────────────────────────────────────────────────────
configure_openbsd_httpd() {
    echo "--- Configuring OpenBSD httpd ---"

    if ! grep -q "$DOMAIN" /etc/httpd.conf 2>/dev/null; then
        cat >> /etc/httpd.conf <<HTTPD

# $DOMAIN — generated by unveil bootstrap
server "$DOMAIN" {
	listen on * port 80
	alias "www.$DOMAIN"
	location "/.well-known/acme-challenge/*" {
		root "/acme"
		request strip 2
	}
	location "*" {
		block return 301 "https://\\\$HTTP_HOST\\\$REQUEST_URI"
	}
}
server "$DOMAIN" {
	listen on * tls port 443
	alias "www.$DOMAIN"
	tls {
		certificate "/etc/ssl/$DOMAIN.fullchain.pem"
		key "/etc/ssl/private/$DOMAIN.key"
	}
	root "/htdocs/$DOMAIN"
	directory index "index.html"
	connection max request body 209715200
	location "*" { pass }
}
HTTPD
        echo "  httpd.conf updated"
    fi

    if [ "$TLS" = "acme" ] && ! grep -q "$DOMAIN" /etc/acme-client.conf 2>/dev/null; then
        cat >> /etc/acme-client.conf <<ACME

authority letsencrypt {
	api url "https://acme-v02.api.letsencrypt.org/directory"
	account key "/etc/acme/letsencrypt-privkey.pem"
}
domain $DOMAIN {
	alternative names { www.$DOMAIN }
	domain key "/etc/ssl/private/$DOMAIN.key"
	domain full chain certificate "/etc/ssl/$DOMAIN.fullchain.pem"
	sign with letsencrypt
}
ACME
        echo "  acme-client.conf updated"
        mkdir -p /var/www/acme
        rcctl enable httpd
        rcctl restart httpd
        acme-client -v "$DOMAIN" \
            && echo "  TLS: OK" \
            || echo "  TLS: run 'acme-client -v $DOMAIN' after DNS is ready"
        (crontab -l 2>/dev/null; echo "0 3 * * * acme-client $DOMAIN && rcctl reload httpd") | sort -u | crontab -
        rcctl restart httpd
    fi
    echo
}

# ── nginx ─────────────────────────────────────────────────────────────────
configure_nginx() {
    echo "--- Configuring nginx ---"

    case "$OS" in
        debian) apt-get install -y -qq nginx ;;
        rhel)   yum install -y nginx ;;
        alpine) apk add nginx ;;
        macos)  brew install nginx ;;
    esac

    if [ -d /etc/nginx/sites-available ]; then
        NGINX_CONF="/etc/nginx/sites-available/$DOMAIN"
        NGINX_LINK="/etc/nginx/sites-enabled/$DOMAIN"
    elif [ -d /etc/nginx/conf.d ]; then
        NGINX_CONF="/etc/nginx/conf.d/$DOMAIN.conf"
        NGINX_LINK=""
    else
        mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled
        NGINX_CONF="/etc/nginx/sites-available/$DOMAIN"
        NGINX_LINK="/etc/nginx/sites-enabled/$DOMAIN"
    fi

    if [ ! -f "$NGINX_CONF" ]; then
        cat > "$NGINX_CONF" <<NGINX
# $DOMAIN — generated by unveil bootstrap
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN www.$DOMAIN;

    location /.well-known/acme-challenge/ {
        root /var/www/acme;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN www.$DOMAIN;

    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

    root $HTDOCS_DIR;
    index index.html;

    client_max_body_size 200m;

    location ~* \.(css|js|pdf|png|jpg|gif|ico|svg)\$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
NGINX
        echo "  nginx config: $NGINX_CONF"
    fi

    [ -n "$NGINX_LINK" ] && [ ! -e "$NGINX_LINK" ] && ln -s "$NGINX_CONF" "$NGINX_LINK"

    if [ "$TLS" = "acme" ]; then
        install_certbot
        mkdir -p /var/www/acme
        nginx -t && nginx -s reload 2>/dev/null || systemctl restart nginx
        certbot certonly --webroot -w /var/www/acme \
            -d "$DOMAIN" -d "www.$DOMAIN" \
            --non-interactive --agree-tos --email "$GPG_EMAIL" \
            && echo "  TLS: OK" \
            || echo "  TLS: run certbot manually after DNS is ready"
        nginx -t && nginx -s reload 2>/dev/null || systemctl restart nginx
    fi
    echo
}

# ── Apache ────────────────────────────────────────────────────────────────
configure_apache() {
    echo "--- Configuring Apache ---"

    case "$OS" in
        debian) apt-get install -y -qq apache2 && a2enmod ssl rewrite headers ;;
        rhel)   yum install -y httpd mod_ssl ;;
        alpine) apk add apache2 apache2-ssl ;;
    esac

    if [ -d /etc/apache2/sites-available ]; then
        APACHE_CONF="/etc/apache2/sites-available/$DOMAIN.conf"
        APACHE_CMD="a2ensite $DOMAIN"
    elif [ -d /etc/httpd/conf.d ]; then
        APACHE_CONF="/etc/httpd/conf.d/$DOMAIN.conf"
        APACHE_CMD=""
    else
        mkdir -p /etc/apache2/sites-available
        APACHE_CONF="/etc/apache2/sites-available/$DOMAIN.conf"
        APACHE_CMD="a2ensite $DOMAIN"
    fi

    if [ ! -f "$APACHE_CONF" ]; then
        cat > "$APACHE_CONF" <<APACHE
# $DOMAIN — generated by unveil bootstrap
<VirtualHost *:80>
    ServerName $DOMAIN
    ServerAlias www.$DOMAIN
    DocumentRoot $HTDOCS_DIR

    Alias /.well-known/acme-challenge/ /var/www/acme/.well-known/acme-challenge/

    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge/
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>

<VirtualHost *:443>
    ServerName $DOMAIN
    ServerAlias www.$DOMAIN
    DocumentRoot $HTDOCS_DIR

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/$DOMAIN/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/$DOMAIN/privkey.pem

    LimitRequestBody 209715200

    <Directory $HTDOCS_DIR>
        Options -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    <LocationMatch "\.(css|js|pdf|png|jpg|gif|ico|svg)\$">
        Header set Cache-Control "public, max-age=604800, immutable"
    </LocationMatch>
</VirtualHost>
APACHE
        echo "  Apache config: $APACHE_CONF"
    fi

    [ -n "$APACHE_CMD" ] && $APACHE_CMD 2>/dev/null || true

    if [ "$TLS" = "acme" ]; then
        install_certbot
        mkdir -p /var/www/acme/.well-known/acme-challenge
        apachectl graceful 2>/dev/null || \
            systemctl restart apache2 2>/dev/null || \
            systemctl restart httpd
        certbot certonly --webroot -w /var/www/acme \
            -d "$DOMAIN" -d "www.$DOMAIN" \
            --non-interactive --agree-tos --email "$GPG_EMAIL" \
            && echo "  TLS: OK" \
            || echo "  TLS: run certbot manually after DNS is ready"
        apachectl graceful 2>/dev/null || \
            systemctl restart apache2 2>/dev/null || \
            systemctl restart httpd
    fi
    echo
}

# ── Caddy ─────────────────────────────────────────────────────────────────
configure_caddy() {
    echo "--- Configuring Caddy ---"

    case "$OS" in
        debian)
            if ! command -v caddy >/dev/null 2>&1; then
                apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl
                curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | \
                    gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
                curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | \
                    tee /etc/apt/sources.list.d/caddy-stable.list
                apt-get update -qq && apt-get install -y -qq caddy
            fi
            ;;
        rhel)   yum install -y caddy ;;
        alpine) apk add caddy ;;
        macos)  brew install caddy ;;
    esac

    CADDY_CONF="/etc/caddy/Caddyfile"
    mkdir -p /etc/caddy

    if [ ! -f "$CADDY_CONF" ] || ! grep -q "$DOMAIN" "$CADDY_CONF" 2>/dev/null; then
        cat >> "$CADDY_CONF" <<CADDY

# $DOMAIN — generated by unveil bootstrap
$DOMAIN, www.$DOMAIN {
    root * $HTDOCS_DIR
    file_server

    request_body {
        max_size 200MB
    }

    @static path *.css *.js *.pdf *.png *.jpg *.gif *.ico *.svg
    header @static Cache-Control "public, max-age=604800, immutable"
}
CADDY
        echo "  Caddyfile: $CADDY_CONF"
        echo "  Caddy handles TLS automatically — no certbot needed"
    fi

    systemctl enable caddy 2>/dev/null || true
    systemctl restart caddy 2>/dev/null || caddy reload --config "$CADDY_CONF" 2>/dev/null || true
    echo
}

# ── Run server config ─────────────────────────────────────────────────────
set_htdocs_owner

case "$HTTPD" in
    openbsd-httpd) configure_openbsd_httpd ;;
    nginx)         configure_nginx ;;
    apache)        configure_apache ;;
    caddy)         configure_caddy ;;
    none)          echo "--- Web server: none (skipped) ---"; echo ;;
    *)             echo "Unknown HTTPD: $HTTPD" >&2; exit 1 ;;
esac

# ── Run setup ─────────────────────────────────────────────────────────────
sh "$UTILS_DIR/setup.sh"

echo
echo "=== Bootstrap complete ==="
echo
echo "Next steps:"
echo "  1. Copy files into $UTILS_DIR/{html,pdf,...}/"
echo "     or drop them into $UTILS_DIR/add/"
echo "  2. Publish:  cd $UTILS_DIR && sh merge.sh"
[ "$HTTPD" != "none" ] && echo "  3. Visit:    https://$DOMAIN/"
