# /etc/acme-client.conf - Let's Encrypt for dpcpbp.org

authority letsencrypt {
	api url "https://acme-v02.api.letsencrypt.org/directory"
	account key "/etc/acme/letsencrypt-privkey.pem"
}

domain dpcpbp.org {
	alternative names { www.dpcpbp.org }
	domain key "/etc/ssl/private/dpcpbp.org.key"
	domain full chain certificate "/etc/ssl/dpcpbp.org.fullchain.pem"
	sign with letsencrypt
}
